=== nikolina97/xws-tim16-siit-2019/backend/src/main/resources/schemas/scientific_paper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/nikolina97/xws-tim16-siit-2019"
    xmlns:sp="https://github.com/nikolina97/xws-tim16-siit-2019"
    xmlns="https://github.com/nikolina97/xws-tim16-siit-2019" vc:maxVersion="1.1"
    vc:minVersion="1.0" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
    <xs:include schemaLocation="utils.xsd"/>
    <xs:element name="scientific_paper">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:anyAttribute namespace="##local" processContents="skip"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="authors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="1" ref="author"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="abstract">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="paragraph" type="TParagraph" maxOccurs="unbounded"
                                minOccurs="1"> </xs:element>
                            <xs:element name="keywords">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="keyword">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:anyAttribute namespace="##local" processContents="skip"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="chapters">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="chapter" type="TChapter" maxOccurs="unbounded"
                                minOccurs="1"> </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="references" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="reference" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="TReference">
                                            <xs:attribute name="id" type="xs:string" use="optional"/>
                                            <xs:anyAttribute namespace="##local" processContents="skip"/>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="PK">
                        <xs:selector xpath="sp:reference"/>
                        <xs:field xpath="sp:ref_number"/>
                    </xs:key>
                </xs:element>
                <xs:element name="comments" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="1" name="comment"
                                type="TParagraph"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="category">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:anyAttribute namespace="##local" processContents="skip"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element form="qualified" minOccurs="0" name="version">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:positiveInteger">
                                <xs:anyAttribute namespace="##local" processContents="skip"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="dateReceived">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:anyAttribute namespace="##local" processContents="skip"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="dateRevised">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:anyAttribute namespace="##local" processContents="skip"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="dateAccepted">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:anyAttribute namespace="##local" processContents="skip"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="state" type="TSPState"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
            <xs:anyAttribute namespace="##local" processContents="skip"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TChapter">
        <xs:sequence>
            <xs:element maxOccurs="1" name="subtitle">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="paragraph" type="TParagraph" maxOccurs="unbounded" minOccurs="1"> </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="subchapter" type="TChapter"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="TParagraph" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="unbounded" minOccurs="0" name="text" type="TDecorator"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="table" type="TTable"/>
            <xs:element name="ref" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="refId" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="quote">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="from" type="xs:string"/>
                        <xs:element name="content" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="figure" type="TImage"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="formula" type="xs:string"> </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="list" type="TList"/>
        </xs:choice>
        <xs:attribute name="id" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="TReference">
        <xs:sequence>
            <xs:element name="ref_number">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\[\d\]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element maxOccurs="unbounded" name="ref_author" type="xs:string"/>
            <xs:element name="article_name" type="xs:string"> </xs:element>
            <xs:element name="year" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TTableRow">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="td" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TImage">
        <xs:sequence>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="image" type="xs:base64Binary"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="TTable">
        <xs:sequence>
            <xs:element name="th" type="TTableRow" minOccurs="0"/>
            <xs:element maxOccurs="unbounded" name="tr" type="TTableRow"/>
            <xs:element name="description" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TFormula">
        <xs:choice>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="var1" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="var2" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="add" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="subtract" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="multiply" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="divide" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="equal" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="subformula" type="TFormula"/>
        </xs:choice>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TList">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="decorator" type="TDecorator"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TDecorator">
        <xs:choice maxOccurs="unbounded" minOccurs="1">
            <xs:element maxOccurs="unbounded" minOccurs="0" name="bold" type="TDecorator"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="italic" type="TDecorator"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="underline" type="TDecorator"/>
        </xs:choice>
    </xs:complexType>
    <xs:element name="author" type="TPerson"/>
    <xs:simpleType name="TSPState">
        <xs:restriction base="xs:string">
            <xs:enumeration value="in_procedure"/>
            <xs:enumeration value="accepted"/>
            <xs:enumeration value="rejected"/>
            <xs:enumeration value="revoked"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== nikolina97/xws-tim16-siit-2019/backend/src/main/resources/schemas/abc1.xml
<?xml version="1.0" encoding="UTF-8"?>
<sp:scientific_paper xmlns:sp="https://github.com/nikolina97/xws-tim16-siit-2019"
 xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/nikolina97/xws-tim16-siit-2019 file:/D:/xml/projekatv3/xws-tim16-siit-2019/backend/src/main/resources/schemas/scientific_paper.xsd" id="id0">
    <sp:title>title0</sp:title>
    <sp:authors>
        <sp:author>
            <sp:first_name>first_name0</sp:first_name>
            <sp:last_name>last_name0</sp:last_name>
            <sp:university>
                <sp:name>name0</sp:name>
                <sp:city>city0</sp:city>
                <sp:country>country0</sp:country>
            </sp:university>
            <sp:email>0@00.AA</sp:email>
            <sp:expertise>expertise0</sp:expertise>
            <sp:expertise>expertise1</sp:expertise>
        </sp:author>
        <sp:author>
            <sp:first_name>first_name1</sp:first_name>
            <sp:last_name>last_name1</sp:last_name>
            <sp:university>
                <sp:name>name1</sp:name>
                <sp:city>city1</sp:city>
                <sp:country>country1</sp:country>
            </sp:university>
            <sp:email>0@00.AA</sp:email>
            <sp:expertise>expertise2</sp:expertise>
            <sp:expertise>expertise3</sp:expertise>
        </sp:author>
    </sp:authors>
    <sp:abstract id="id1">
        <sp:paragraph id="id2">
            <sp:table id="id3">
                <sp:th>
                    <sp:td>td0</sp:td>
                    <sp:td>td1</sp:td>
                </sp:th>
                <sp:tr>
                    <sp:td>td2</sp:td>
                    <sp:td>td3</sp:td>
                </sp:tr>
                <sp:tr>
                    <sp:td>td4</sp:td>
                    <sp:td>td5</sp:td>
                </sp:tr>
                <sp:description>description0</sp:description>
            </sp:table>
            <sp:table id="id4">
                <sp:th>
                    <sp:td>td6</sp:td>
                    <sp:td>td7</sp:td>
                </sp:th>
                <sp:tr>
                    <sp:td>td8</sp:td>
                    <sp:td>td9</sp:td>
                </sp:tr>
                <sp:tr>
                    <sp:td>td10</sp:td>
                    <sp:td>td11</sp:td>
                </sp:tr>
                <sp:description>description1</sp:description>
            </sp:table>
            <sp:text>
                <sp:italic>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                </sp:italic>
                <sp:italic>
                    <sp:underline>
                    </sp:underline>
                    <sp:underline>
                    </sp:underline>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                </sp:italic>
                <sp:underline>
                    <sp:italic>
                    </sp:italic>
                    <sp:italic>
                    </sp:italic>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                </sp:underline>
                <sp:underline>
                    <sp:italic>
                    </sp:italic>
                    <sp:italic>
                    </sp:italic>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                </sp:underline>
            </sp:text>
            <sp:text>
                <sp:bold>
                    <sp:italic>
                    </sp:italic>
                    <sp:italic>
                    </sp:italic>
                    <sp:italic>
                    </sp:italic>
                    <sp:italic>
                    </sp:italic>
                </sp:bold>
                <sp:bold>
                    <sp:italic>
                    </sp:italic>
                    <sp:italic>
                    </sp:italic>
                    <sp:italic>
                    </sp:italic>
                    <sp:italic>
                    </sp:italic>
                </sp:bold>
                <sp:italic>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                </sp:italic>
                <sp:italic>
                    <sp:underline>
                    </sp:underline>
                    <sp:underline>
                    </sp:underline>
                    <sp:bold>
                    </sp:bold>
                    <sp:bold>
                    </sp:bold>
                </sp:italic>
            </sp:text>
        </sp:paragraph>
        <sp:paragraph id="id5">
            <sp:formula>formula0</sp:formula>
            <sp:formula>formula1</sp:formula>
            <sp:figure id="id6">
                <sp:description>description2</sp:description>
                <sp:image>ZGVmYXVsdA==</sp:image>
            </sp:figure>
            <sp:figure id="id7">
                <sp:description>description3</sp:description>
                <sp:image>ZGVmYXVsdA==</sp:image>
            </sp:figure>
        </sp:paragraph>
        <sp:keywords>
            <sp:keyword>keyword0</sp:keyword>
            <sp:keyword>keyword1</sp:keyword>
        </sp:keywords>
    </sp:abstract>
    <sp:chapters>
        <sp:chapter id="id8">
            <sp:subtitle>subtitle0</sp:subtitle>
            <sp:paragraph id="id9">
                <sp:formula>formula2</sp:formula>
                <sp:formula>formula3</sp:formula>
                <sp:ref refId="refId0">ref0</sp:ref>
                <sp:ref refId="refId1">ref1</sp:ref>
            </sp:paragraph>
            <sp:paragraph id="id10">
                <sp:ref refId="refId2">ref2</sp:ref>
                <sp:ref refId="refId3">ref3</sp:ref>
                <sp:ref refId="refId4">ref4</sp:ref>
                <sp:ref refId="refId5">ref5</sp:ref>
            </sp:paragraph>
            <sp:subchapter id="id11">
                <sp:subtitle>subtitle1</sp:subtitle>
                <sp:paragraph id="id12">
                    <sp:text>
                    </sp:text>
                    <sp:text>
                    </sp:text>
                    <sp:figure id="id13">
                        <sp:description>description4</sp:description>
                        <sp:image>ZGVmYXVsdA==</sp:image>
                    </sp:figure>
                    <sp:figure id="id14">
                        <sp:description>description5</sp:description>
                        <sp:image>ZGVmYXVsdA==</sp:image>
                    </sp:figure>
                </sp:paragraph>
                <sp:paragraph id="id15">
                    <sp:formula>formula4</sp:formula>
                    <sp:formula>formula5</sp:formula>
                    <sp:text>
                    </sp:text>
                    <sp:text>
                    </sp:text>
                </sp:paragraph>
                <sp:paragraph id="id16">
                    <sp:table id="id17">
                        <sp:tr>
                            <sp:td>td12</sp:td>
                            <sp:td>td13</sp:td>
                        </sp:tr>
                        <sp:tr>
                            <sp:td>td14</sp:td>
                            <sp:td>td15</sp:td>
                        </sp:tr>
                        <sp:description>description6</sp:description>
                    </sp:table>
                    <sp:table id="id18">
                        <sp:tr>
                            <sp:td>td16</sp:td>
                            <sp:td>td17</sp:td>
                        </sp:tr>
                        <sp:tr>
                            <sp:td>td18</sp:td>
                            <sp:td>td19</sp:td>
                        </sp:tr>
                        <sp:description>description7</sp:description>
                    </sp:table>
                    <sp:figure id="id19">
                        <sp:description>description8</sp:description>
                        <sp:image>ZGVmYXVsdA==</sp:image>
                    </sp:figure>
                    <sp:figure id="id20">
                        <sp:description>description9</sp:description>
                        <sp:image>ZGVmYXVsdA==</sp:image>
                    </sp:figure>
                </sp:paragraph>
                <sp:paragraph id="id21">
                    <sp:formula>formula6</sp:formula>
                    <sp:formula>formula7</sp:formula>
                    <sp:formula>formula8</sp:formula>
                    <sp:formula>formula9</sp:formula>
                </sp:paragraph>
            </sp:subchapter>
            <sp:subchapter id="id22">
                <sp:subtitle>subtitle2</sp:subtitle>
                <sp:paragraph id="id23">
                    <sp:ref refId="refId6">ref6</sp:ref>
                    <sp:ref refId="refId7">ref7</sp:ref>
                    <sp:figure id="id24">
                        <sp:description>description10</sp:description>
                        <sp:image>ZGVmYXVsdA==</sp:image>
                    </sp:figure>
                    <sp:figure id="id25">
                        <sp:description>description11</sp:description>
                        <sp:image>ZGVmYXVsdA==</sp:image>
                    </sp:figure>
                </sp:paragraph>
                <sp:paragraph id="id26">
                    <sp:quote>
                        <sp:from>from0</sp:from>
                        <sp:content>content0</sp:content>
